printf(
"Suricata Configuration:\n"
"  AF_PACKET support:                       no\n"
"  DPDK_INTEL support:                      yes\n"
"  PF_RING support:                         no\n"
"  NFQueue support:                         no\n"
"  NFLOG support:                           no\n"
"  IPFW support:                            no\n"
"  Netmap support:                          no\n"
"  DAG enabled:                             no\n"
"  Napatech enabled:                        no\n"
"\n"
"  Unix socket enabled:                     no\n"
"  Detection enabled:                       yes\n"
"\n"
"  libnss support:                          no\n"
"  libnspr support:                         no\n"
"  libjansson support:                      no\n"
"  hiredis support:                         no\n"
"  Prelude support:                         no\n"
"  PCRE jit:                                yes\n"
"  LUA support:                             no\n"
"  libluajit:                               no\n"
"  libgeoip:                                no\n"
"  Non-bundled htp:                         no\n"
"  Old barnyard2 support:                   no\n"
"  CUDA enabled:                            no\n"
"\n"
"  Suricatasc install:                      yes\n"
"\n"
"  Unit tests enabled:                      no\n"
"  Debug output enabled:                    no\n"
"  Debug validation enabled:                no\n"
"  Profiling enabled:                       no\n"
"  Profiling locks enabled:                 no\n"
"  Coccinelle / spatch:                     no\n"
"\n"
"Generic build parameters:\n"
"  Installation prefix:                     /home/vipin/DPDK-Suricata_3.0/suricata-3.0/myconf\n"
"  Configuration directory:                 /home/vipin/DPDK-Suricata_3.0/suricata-3.0/suricata/\n"
"  Log directory:                           /home/vipin/DPDK-Suricata_3.0/suricata-3.0/myconf/var/log/suricata/\n"
"\n"
"  --prefix                                 /home/vipin/DPDK-Suricata_3.0/suricata-3.0/myconf\n"
"  --sysconfdir                             /home/vipin/DPDK-Suricata_3.0/suricata-3.0\n"
"  --localstatedir                          /home/vipin/DPDK-Suricata_3.0/suricata-3.0/myconf/var\n"
"\n"
"  Host:                                    x86_64-pc-linux-gnu\n"
"  Compiler:                                gcc (exec name) / gcc (real)\n"
"  GCC Protect enabled:                     no\n"
"  GCC march native enabled:                yes\n"
"  GCC Profile enabled:                     no\n"
"  Position Independent Executable enabled: no\n"
"  CFLAGS                                   -g -O2 -march=native -DHAVE_DPDKINTEL -I/home/vipin/DPDK-Suricata_3.0/dpdk-stable-18.11.5/x86_64-native-linuxapp-gcc/include/ -include /home/vipin/DPDK-Suricata_3.0/dpdk-stable-18.11.5/x86_64-native-linuxapp-gcc/include/rte_config.h \n"
"  PCAP_CFLAGS                               -I/usr/include\n"
"  SECCFLAGS                                \n"
);
